1. Automatic Derivation

In [1]:
import torch
x=torch.arange(4.0) # Create a tensor with 0.0, 1.0, 2.0, 3.0
x

tensor([0., 1., 2., 3.])

In [2]:
x.requires_grad_(True) # The same function as 'x.requires_grad=True', but it's more convenient for further chain rule
x.grad

In [3]:
y=2*torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

In [4]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [5]:
x.grad==4*x

tensor([True, True, True, True])

In [6]:
x.grad.zero_() # Clear all the gradients in x.grad (Or pytorch would automatically accumulate the gradients)
y=x.sum() # Sum up all the elements in x (y=x_1+x_2+x_3+x_4)
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [7]:
x.grad.zero_()
y=x*x #Here y is also a vector
y=x.sum().backward() # In most cases, we don't use two vectors to make derivations
x.grad

tensor([1., 1., 1., 1.])

In [8]:
x.grad.zero_()
y=x*x
u=y.detach() # We isolated u from x
z=u*x

z.sum().backward()
x.grad == u 

tensor([True, True, True, True])

In [9]:
x.grad.zero_()
y.sum().backward()
x.grad==2*x

tensor([True, True, True, True])

In [ ]:
def f(a):
    b=a*2
    while b.norm()<1000:
        b=b*2
    if b.sum()>0:
        c=b
    else:
        c=100*b
    return c
a=torch.randn(size=(), requires_grad=True) # a is a scalar with random number
d=f(a)
d.backward()
a.grad ==d/a # It's always a linear function of a, so the gradient would be y/x

tensor(True)